### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by soadev** [michaelbeutler/edubase-to-pdf#1]
Hello, can you help me to download my files ? i have an error : from the page 5, the download is blocked

**Comment by soadev** [comment]
![image](https://user-images.githubusercontent.com/72621534/135237190-4cb7fee6-0064-410f-b1cc-388402b9c193.png)

**Comment by michaelbeutler** [comment]
Hello there,

It seems that there is no element matching the given selector. 

```javascript
document.querySelector(".lu-page-svg-container svg");
```

You maybe have to inspect the page and search for alternative selectors. If you need further help, feel free to send me a screenshot of the rendered elements.

**Comment by soadev** [comment]
Hello again, thank you for your answer.
Would it be possible to do it to me with anydesk or with teamviewer to show me how it works?

**Comment by michaelbeutler** [comment]
Yeah, sure... I write you an email tomorrow.
