### ISSUE TITLE
Problems Logging in

### ISSUE THREAD

**Issue by spicndsoicsimp** [michaelbeutler/edubase-to-pdf#10]
I downloaded and started the program edbubase to pdf in git bash and it kinda works. the problem is as soon as i type in my acc. data it says Could not login: Login failed (Could not find account button). my edubase Acc is a google acc. but my email and password for this google acc should be enough right? would be nice if you could help me out. thanks:)

![image](https://github.com/user-attachments/assets/86583f65-0a87-452a-9db0-780f89036f67)

There's a new problem now. i tryed it with a new acc which isn't linked with google and there the login works but as soon as i try to download these free books which are available theres another message:

$  edubase-to-pdf import -e ***************** -p *********** -s 10 -m 20
2024/10/23 18:50:53 Downloading browsers...
2024/10/23 18:50:54 Downloaded browsers successfully
   0% |                                               | (0/20, 0 it/hr) [0s:0s]2024/10/23 18:51:09 could not take screenshot: could not create screenshot: open screenshots/62244_10.jpeg: The system cannot find the path specified.

the * are just for safety;)

**Comment by michaelbeutler** [comment]
Sign in only works with native accounts, I haven't implemented the OAuth2 flow. Regarding the path issue, please try to create the screenshots folder manually.

**Comment by spicndsoicsimp** [comment]
I found a workaround for my logg-in Problem and managed to change the folder where the screenshots will be safed at. Thanks a lot for this code! You made my daily studys much more efficient!Von: Michael Beutler ***@***.***>Gesendet: Mittwoch, 23. Oktober 2024 um 20:48An: michaelbeutler/edubase-to-pdf ***@***.***>Cc: spicndsoicsimp ***@***.***>; Author ***@***.***>Betreff: Re: [michaelbeutler/edubase-to-pdf] Problems Logging in (Issue #10)
Sign in only works with native accounts, I haven't implemented the OAuth2 flow. Regarding the path issue, please try to create the screenshots folder manually.

**Comment by kinba3000** [comment]
Seams to be solved.
