### ISSUE TITLE
Not showing books

### ISSUE THREAD

**Issue by JamieGerber** [michaelbeutler/edubase-to-pdf#11]
Hallo, aufgrund deiner Beispiele gehe ich davon aus, dass du Deutsch sprichst :D

Ich wollte mit folgendem Befehl meine Edubase bücher herunterladen:
**edubase-to-pdf import -s 2 -m 10**

Jedoch werden mir keine Bücher angezeigt:
<img width="1251" alt="Screenshot 2024-11-20 at 20 40 38" src="https://github.com/user-attachments/assets/38ffa3f5-4819-46c9-8e24-b62303c663e7">

Der Account besteht und das Passwort ist auch richtig, da ich mich bei Edubase problemlos anmelden kann.

Ich hoffe du kannst mir da helfen :)

**Comment by michaelbeutler** [comment]
Hallo, kommt nach dem Login ein Popup oder Derartiges?
