### ISSUE TITLE
Where is it saved?

### ISSUE THREAD

**Issue by Tonrad** [michaelbeutler/edubase-to-pdf#12]
Hello,

First: thanks a lot for your skript. its awesome.
Now i have a smal question, where will the PDF be saved? i cannot find it.

Thx for youre Time.

**Comment by michaelbeutler** [comment]
Hello, thanks for the positive feedback.

The resulting PDF will be saved in the current directory.

**Comment by Tonrad** [comment]
Do you mean here?
![image](https://github.com/user-attachments/assets/cd23d7ea-dc74-4bc3-a23f-d8d6082a1120)

**Comment by michaelbeutler** [comment]
Hi there! I believe you may have referenced the wrong GitHub repository. This particular tool is written in Go, so it might not align with the context you're looking for.
