### ISSUE TITLE
Merci

### ISSUE THREAD

**Issue by AndrinGautschi** [michaelbeutler/edubase-to-pdf#2]
Merci villmal fürd Idee! Han lang nach möglichkeite gsuecht, zum die Büecher abezlade. Leider het din asatz was formatting abelangt en wurm drin (tabelle outline werded nöd übernoh, sache ligged überenand). 

Han druf abe "schnell" selber was zemecoded (andere asatz mit puppeteer) für de Fall dassds mal bruchsch: https://github.com/AndrinGautschi/edubase-book-downloader

**Comment by figugegu** [comment]
Sali Andrin
Ich versuchte gerade dein Script auszuführen. Super Idee.
Aber ich bekomme immer einen Error Timeout. Kannst du mir vielleicht bei der Lösung helfen? Ich habe zu wenig verständnis dafür...
`C:\edubase-book-downloader-main>node .
2022-09-09T19:17:37.567Z  --- try to log in
2022-09-09T19:18:00.515Z  --- logged in
2022-09-09T19:18:01.046Z  --- opened page with book
C:\edubase-book-downloader-main\node_modules\puppeteer\lib\cjs\puppeteer\common\helper.js:120
            rejectCallback(new Errors_js_1.TimeoutError('Timeout exceeded while waiting for event'));
                           ^

TimeoutError: Timeout exceeded while waiting for event
    at Timeout.<anonymous> (C:\edubase-book-downloader-main\node_modules\puppeteer\lib\cjs\puppeteer\common\helper.js:120:28)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)`

**Comment by AndrinGautschi** [comment]
Hoi @figugegu 
Aufgrund mangelnder Hardware (kein Laptop) kann ich das Issue nicht nachstellen. Ich kann aber einen Tipp geben; 
Das Script stirbt auf [dieser Zeile](https://github.com/AndrinGautschi/edubase-book-downloader/blob/main/index.js#L39).
Hier warte ich auf einen Request, dessen Ausführung das „fertig rendern“ der Webseite indiziert. [Hier](https://github.com/AndrinGautschi/edubase-book-downloader/blob/main/index.js#L74) wird diese Variable abgefüllt. 

Geh mal auf eine Seite des Buches, das du konvertieren willst, öffne die DEV-Tools (F12), navigiere zum „Network“ Tab in den DEV-Tools, klicke auf „nächste Seite“ auf der Edubase Page und schaue mal die Requests an, die die Seite generiert. Wahrscheinlich findest du einen ähnlichen Request, der sich aber durch eine Versionsnummer oder sonstige Details unterscheidet. Einfach den in die Variable kopieren und nochmals versuchen. Ich werde es mir in ein paar Tagen mal anschauen, sobald ich Zeit und Zugang zu meinem Laptop habe heisst das. 

LG
