### ISSUE TITLE
Please help me with Yarn - point 7

### ISSUE THREAD

**Issue by Sinon97** [michaelbeutler/edubase-to-pdf#3]
Dear Mister Beutler,

I'm so sorry, but I have some problems in point 7, nothing works.
My knowledge isn't enough and I don't really understand, what I must doing.
Till point 6, I understand exactly, but then only errors.

Please can you help me understand or can you more exactly say, what I must do by point 6 till 9 with the correct commands?
When I run "node .", it's never working for me.

I have seen, you are from Switzerland? So then german is your mother language?
If you like, you can say in german, because it's more easy for me, too.
And yes, I'm absolutly a beginner in Java, Node and Yarn, so I can't see the right way.

Best regards
Sinon

**Comment by michaelbeutler** [comment]
Hallo Sinon

Hast du `yarn`bereits installiert? (`npm install -g yarn`)
Kannst du mir eventuell die Fehlermeldung zeigen?

Gruss
Michael

**Comment by Sinon97** [comment]
Hallo Michael,

Danke für die schnelle Antwort. Der Installationsbefehl scheint schonmal geklappt zu haben:

faunus@faunus-Aspire-VN7-793G:~$ sudo npm install -g yarn

changed 1 package, and audited 2 packages in 1s

found 0 vulnerabilities

Wenn ich "node ." oder "sudo node s" mache bekomme ich dann folgende Meldung:
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '/home/faunus/Schreibtisch/edubase-to-pdf-main/s'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []

Ist es eventuell sonst möglich via Teamviewer zu arbeiten? Ich glaube im Endeffekt wäre es eine Arbeit von 5-10 Minuten, wenn man ein Profi ist.

Liebe Grüsse
Sinon

**Comment by michaelbeutler** [comment]
Klar, adde mich auf Discord. Michael Beutler#7891
