### ISSUE TITLE
Keine Ahnung wie ich das machen muss

### ISSUE THREAD

**Issue by Timi1543** [michaelbeutler/edubase-to-pdf#5]
Hallo Erstmal die idee finde ich super. Jedoch habe ich gar keine erfahrung mit Programmieren und allgemein mit Java und so. Jetzt wollte ich fragen ob du mir vielleicht die Anleitung etwas vereinfachen könntest weil ab dem Punkt Maxpages oder so verstehe ich schon nicht mehr ganz was ich machen muss. Wäre mega nett. LG

**Comment by Timi1543** [comment]
Wäre vielleicht ein YouTube Tutorial oder so möglich? Ich weiss nicht genau wo ich was in den Entwicklertools einfüllen muss und welche Dateien ich von dir benutzen muss.

**Comment by michaelbeutler** [comment]
Hallo @Timi1543, vielen Dank für dein Interesse. Leider habe ich keinen aktiven Zugang mehr und kann deshalb kein Video machen. An welchem Punkt stehst du aktuell an?

**Comment by Timi1543** [comment]
Ich habe jemanden gefragt. Es hat funktioniert aber danke für die Antwort.
